version: "3.1"

services:
  notion-api-service:
    env_file: .env
    environment:
      - MONGOOSE_URI=mongodb://mongo:27018/sipoenglish
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:4.2.8
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
