name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      USE_DEFAULT_USER: false
      MAX_UPLOAD_LIMIT: 2000
      PORT: ${{ secrets.PORT }}
      MONGOOSE_URI: ${{ secrets.MONGOOSE_URI }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_OAUTH_ID: ${{ secrets.NOTION_TOKEN }}
      NOTION_OAUTH_SECRET: ${{ secrets.NOTION_OAUTH_SECRET }}
      FIREBASE_ADMIN_PATH: ${{ secrets.FIREBASE_ADMIN_PATH }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
